# This is a basic workflow to help you get started with Actions

name: Angular Build Pipeline
run-name: Angular Build Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout github
        uses: actions/checkout@v4
        
      - name: aws login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          # AWS Secret Access Key. Required if aws-access-key-id is provided.
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: install node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 16
          
      - name: install dependencies
        run: npm install

      - name: build app
        run: npm run build

      - name: deploy to s3 bucket
        run: aws s3 sync actions-demo/dist/actions-demo s3://actions-demo-pje
        
    #more builds that would run in parallel here
